version: '3.8'

services:
  comments-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - test-db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "comments-system"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5452:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test-comments-system"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5453:5432"
    volumes:
      - test_pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  test_pg_data:
