// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        int       `json:"id"`
	PostID    int       `json:"postId"`
	ParentID  *int      `json:"parentId,omitempty"`
	AuthorID  int       `json:"authorId"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}

type Mutation struct {
}

type Post struct {
	ID               int       `json:"id"`
	Title            string    `json:"title"`
	Content          string    `json:"content"`
	AuthorID         int       `json:"authorId"`
	CommentsDisabled bool      `json:"commentsDisabled"`
	CreatedAt        time.Time `json:"createdAt"`
}

type Query struct {
}

type Subscription struct {
}
